[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComplexRegions = "c64915e2-6c82-11e9-38e9-1f159a780463"
ComplexValues = "41a84b80-6cf2-11e9-379d-9df124847946"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
ComplexRegions = {rev = "master", url = ".."}

[compat]
Documenter = "1"
